apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: python-app
  name: hpa-python-app
  namespace: python
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-app
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 10
