apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-vol
  namespace: python
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  awsElasticBlockStore:
    volumeID: aws://ap-south-1c/vol-0ae066df9ed191b3e
    fsType: xfs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-retain
  volumeMode: Filesystem
