apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-vol
  labels:
    app: python
  namespace: python
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: python-vol

